networks:
  net:
    driver: bridge
services:
  authservice:
    container_name: authservice
    restart: unless-stopped
    build:
      context: ./auth/
    image: authservice
    volumes:
      - ./auth/src:/app/src
    networks:
      - net
    ports:
      - "7000"
  front:
    container_name: front
    restart: unless-stopped
    build:
      context: ./front/
    image: front
    volumes:
      - ./front/src:/app/src
      - ./front/public:/app/public
    networks:
      - net
    ports:
      - "3000"
  mongo:
    container_name: mongo
    image: mongo
    restart: unless-stopped
    volumes:
      - ./mongodb/database:/data/db
    networks:
      - net
    ports:
      - "27017:27017"
  proxy:
    container_name: proxy
    image: nginx
    restart: unless-stopped
    depends_on:
      - authservice
      - front
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - net
    ports:
      - "3080:80"